name: CI/CD

on:                                  # Event 감지
  push:
    branches:
      - main                        
jobs:                                # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies    # 의존 파일 설치
        run: npm install --frozen-lockfile

      - name: Build                   # React Build
        run: npm run build
      
      - name: Deploy                  # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.SECRET_KEY }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://github-angular-cli-issue-list
